export const GET_SHOWS_FAILED = 'GET_SHOWS_FAILED';
export const GET_SHOWS_INIT = 'GET_SHOWS_INIT';
export const GET_SHOWS_SUCCESS = 'GET_SHOWS_SUCCESS';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE'